baseURL = "http://escoffier.me/snowcamp"
languageCode = "fr"
title = "Snowcamp 2018"
googleAnalytics = ""

DefaultContentLanguage = "fr"

[Languages]

[Languages.fr]
weight = 1
[Languages.en]
weight = 2

